### ISSUE TITLE
Entry vs exit?

### ISSUE THREAD

**Issue by jrappen** [deathaxe/sublime-skins#5]
I'd like to be able to apply settings (or remove them by using `null`) when switching away from a skin, not only to it.

**Comment by deathaxe** [comment]
This is indeed something I already thought about as some skins/themes leave a lot of rubbish around. The question is how to accomplish that reasonably without the risk to delete settings a user doesn't want to be deleted. I'd need to create some kind of snapshot of all settings being applied by a skin and revert them, before applying a new one.

**Comment by jrappen** [comment]
I guess we can close this as `wontfix`
